// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_MainWindow.cpp"
#include "EWIEGA46WW/moc_registrationlist.cpp"
#include "EWIEGA46WW/moc_registrationlistwriter.cpp"
